nameOverride: project-nextjs
fullnameOverride: project-nextjs

web:
  imagePullPolicy: IfNotPresent
  imagePullSecrets: ''
  image: dborovskiy00/nextjs:4.0.1
  terminationGracePeriodSeconds: 0
  replicaCount: 2

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  cachePersistentVolume:
    enabled: false
    storageClass: nfs-project-app
    existingClaim: ''
    accessModes:
      - ReadWriteOnce
    annotations: {}
    size: 1Gi
    volumeMode: ''
    mountPath: /app/.next/cache

  hpa:
    enabled: false
    maxReplicas: 10
    cpu:
    memory:
    requests:

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    hosts:
      - host: project.k8s-3.sa
        paths:
          - path: /
    tls: []

  service:
    enabled: true
    type: ClusterIP
    port: 3000
    annotations: {}

  livenessProbe:
    enabled: false
    httpGet:
      endpoint: /api/hc?source=livenessProbe
      httpHeaders: []
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 2
    successThreshold: 1
  readinessProbe:
    enabled: false
    httpGet:
      endpoint: /api/hc?source=readinessProbe
      httpHeaders: []
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 2
    successThreshold: 1

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  extraEnvs: []
  # extraEnvs:
  #   - name: AIRBROKE_GITHUB_ID
  #     value: "xxxx"
  #   - name: AIRBROKE_GITHUB_SECRET
  #     value: "xxxxx"
  #   - name: AIRBROKE_GITHUB_ORGS
  #     value: "xxxxx"
  #   - name: NEXTAUTH_SECRET
  #     value: "xxxxxxx"
  #   - name: NEXTAUTH_URL
  #     value: "https://xxxxxx"
  #   - name: AIRBROKE_OPENAI_API_KEY
  #     value: "sk-xxxxxxx"

  podDisruptionBudget:
    enabled: false

    maxUnavailable:

    minAvailable:
