name: Deployment

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Update image version
        run: |
          sed -i 's|image: dborovskiy00/nextjs:.*|image: dborovskiy00/nextjs:${{ github.event.client_payload.version }}|g' values.yaml

      - name: Update Chart version
        run: |
          sed -i 's|version: .*|version: ${{ github.event.client_payload.version }}|g' Chart.yaml

      - name: Package version
        run: |
          cd ./releases
          helm package ../sources
          helm repo index --url https://dborovskiy00.github.io/nextjs-ssr-helm/ ../
          cd ..

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "${{ github.event.client_payload.version }}"
          git push

      - name: Create and push tag
        run: |
          git tag -a ${{ github.event.client_payload.version }} -m "Version ${{ github.event.client_payload.version }}"
          git push origin ${{ github.event.client_payload.version }}

      - name: Trigger deployment in Argocd Repository
        run: |
          repo_owner="${{ secrets.OWNER }}"
          event_type="trigger-workflow"
          version="${{ github.event.client_payload.version }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dborovskiy00/${{ secrets.ARGO_REPO_NAME }}/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"version\": \"$version\", \"unit\": false, \"integration\": true}}"        
